services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      webserver
      --config /freqtrade/user_data/config.json
      --logfile /freqtrade/user_data/logs/freqtrade.log
